[package]
name = "penrose_arlo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.2"
simplelog = "0.12"
tracing = "0.1"
playerctl = "0.1"
xcb = "1.1"
lazy_static = "1.4"
arboard = "2.1"
